import Head from 'next/head';
import { BiUserPlus } from 'react-icons/bi';
import { useDispatch } from 'react-redux';
import { useQueryClient } from 'react-query';
import Table from '@/components/Table';
import Form from '@/components/Form';
import Delete from '@/components/Delete';
import { deleteAction, toggleChangeAction } from '@/store/slices/user.slice';
import { useAppSelector } from '@/hooks/redux';
import { deleteUser, getUsers } from '../lib/helper';

export default function Home() {
  const visible = useAppSelector((state) => state.app.toggleForm);
  const deleteId = useAppSelector((state) => state.app.deleteId);
  const queryclient = useQueryClient();

  const dispatch = useDispatch();

  const handler = () => {
    dispatch(toggleChangeAction());
  };

  const handleDelete = async () => {
    if (deleteId) {
      await deleteUser(deleteId);
      await queryclient.prefetchQuery('users', getUsers);
      dispatch(deleteAction(null));
    }
  };

  const handleCancel = () => {
    dispatch(deleteAction(null));
  };

  return (
    <section>
      <Head>
        <title>CRUD Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-5">
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">Employee Management</h1>

        <div className="container mx-auto flex justify-between py-5 border-b">
          <div className="left flex gap-3">
            <button
              type="button"
              onClick={handler}
              className="flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-grary-50 hover:border-indigo-500 hover:text-gray-800"
            >
              Add Employee{' '}
              <span className="px-1">
                <BiUserPlus size={23} />
              </span>
            </button>
          </div>
          {deleteId && <Delete handleDelete={handleDelete} handleCancel={handleCancel} />}
        </div>

        {visible && <Form />}

        <div className="container mx-auto">
          <Table />
        </div>
      </main>
    </section>
  );
}
